source 'https://rubygems.org'
# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby '>= 2.6.10'
gem 'cocoapods', '>= 1.13', '< 1.15'
gem 'logger'
gem 'benchmark'
gem 'ostruct'
gem 'base64'
gem 'bigdecimal'
gem 'mutex_m'
gem 'abbrev'
gem 'activesupport', '>= 6.1.7.5', '< 7.1.0'
# concurrent-ruby 1.3.5 dropped an implicit `require 'logger'` that activesupport
# 7.0.x relies on, so anything newer breaks `pod install` with
# "uninitialized constant ActiveSupport::LoggerThreadSafeLevel::Logger".
# activesupport is itself held below 7.1 by the cocoapods '< 1.15' pin above,
# so this pin has to stay until both are lifted together.
gem 'concurrent-ruby', '< 1.3.5'