name: Deploy Environment
on:
    workflow_call:
        inputs:
            environment:
                required: true
                type: string
            new_tag:
                required: false
                type: string
permissions:
    id-token: write
    contents: read
jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: ${{inputs.environment}}
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
            - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version: 24
                  registry-url: "https://registry.npmjs.org"
            - name: NPM Install
              run: npm ci
            - name: NPM Audit Fix
              run: npm audit fix
            - if: ${{ inputs.new_tag != '' }}
              name: Set package version from release tag
              run: npm version ${{inputs.new_tag}} --no-git-tag-version --allow-same-version
            - if: ${{ inputs.environment == 'pro' }}
              name: Build Production Files
              run: npm run prepare
            - if: ${{ inputs.environment == 'pro' }}
              name: Publish to NPM
              run: npm publish --access public
